title: "@blacktm"
description: Software engineer exploring graphics, systems, and artificial intelligence
url: https://www.blacktm.com
author:
  name: Tom Black

plugins:
  - jekyll-tailwind
  - jekyll-feed
  - jekyll-sitemap

tailwind:
  input: _css/app.css
  minify: true

kramdown:
  hard_wrap: true

posts_path: /blog
permalink: '/blog/:title'

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
  - scope:
      path: ''
    values:
      layout: main
  - scope:
      path: ''
      type: posts
    values:
      layout: post
